export const usersData = [
  {
    reportedBy: "Alex Carter",
    date: "2025-04-01",
    location: "Building A, Room 101",
    severity: "High",
    assignedTo: "Security Team",
    status: "Needs Attention",
    responseTime: "2 min",
  },
  {
    reportedBy: "Samantha Lee",
    date: "2025-04-01",
    location: "Library Entrance",
    severity: "Medium",
    assignedTo: "Campus Patrol",
    status: "In Progress",
    responseTime: "5 min",
  },
  {
    reportedBy: "Michael Johnson",
    date: "2025-03-31",
    location: "Parking Lot C",
    severity: "Low",
    assignedTo: "Admin",
    status: "Resolved",
    responseTime: "10 min",
  },
  {
    reportedBy: "Emma Williams",
    date: "2025-03-30",
    location: "Dormitory 2, Hallway",
    severity: "High",
    assignedTo: "Emergency Response",
    status: "Needs Attention",
    responseTime: "3 min",
  },
  {
    reportedBy: "Daniel Kim",
    date: "2025-03-30",
    location: "Sports Complex",
    severity: "Medium",
    assignedTo: "Security Team",
    status: "In Progress",
    responseTime: "7 min",
  },
  {
    reportedBy: "Sophia Martinez",
    date: "2025-03-29",
    location: "Main Entrance",
    severity: "Low",
    assignedTo: "Help Desk",
    status: "Resolved",
    responseTime: "15 min",
  }
];
