export const usersData = [
  {
    reportedBy: "John Doe",
    date: "2025-03-31",
    category: "Network",
    severity: "High",
    assignedTo: "Admin",
    status: "Pending",
    responseTime: "2 hrs",
  },
  {
    reportedBy: "Jane Smith",
    date: "2025-03-30",
    category: "Security",
    severity: "Medium",
    assignedTo: "Tech Team",
    status: "Resolved",
    responseTime: "4 hrs",
  },
  {
    reportedBy: "Alice Brown",
    date: "2025-03-29",
    category: "Hardware",
    severity: "Low",
    assignedTo: "Support",
    status: "In Progress",
    responseTime: "6 hrs",
  },
  {
    reportedBy: "Bob White",
    date: "2025-03-28",
    category: "Software",
    severity: "High",
    assignedTo: "Development",
    status: "Pending",
    responseTime: "3 hrs",
  },
  {
    reportedBy: "Eve Black",
    date: "2025-03-27",
    category: "Database",
    severity: "Low",
    assignedTo: "DB Admin",
    status: "Resolved",
    responseTime: "1 hr",
  },
];